/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class Kullaiciliste extends javax.swing.JFrame {

    /**
     * Creates new form Kullaiciliste
     */
    public Kullaiciliste() {
        
        super("Müşteri Cihaz İşlemleri");
        
        initComponents();
         
        String baslik[] = new String[]{"Ad Soyad", "Cihaz Türü", "Nedeni", "Durumu", "Tarihi", "İşlemler", "Ücret"};  
         
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
            
            String sorgu21 = "select * from musteriler";
            rs = st.executeQuery(sorgu21);
            
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("adi_soyadi"),
                    rs.getString("turu"),
                    rs.getString("nedeni"),
                    rs.getString("durumu"),
                    rs.getString("tarihi"),  
                    rs.getString("islemler"),
                    rs.getString("ucreti")
                };
                i++;
            }
           
            table_musteriler.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sil = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_musteriler = new javax.swing.JTable();
        btn_ara = new javax.swing.JButton();
        txt_ara = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        txt_turu = new javax.swing.JTextField();
        txt_ucret = new javax.swing.JTextField();
        txt_tarihi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_islemler = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_nedeni = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_durumu = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 890));
        setPreferredSize(new java.awt.Dimension(690, 890));
        getContentPane().setLayout(null);

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sil);
        btn_sil.setBounds(210, 740, 81, 25);

        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guncelle);
        btn_guncelle.setBounds(110, 740, 81, 25);

        table_musteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Müşteri Ad Soyad", "Cihaz Durumu", "Teslim Tarihi"
            }
        ));
        table_musteriler.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                table_musterilerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table_musteriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_musterilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_musteriler);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 640, 270);

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ara);
        btn_ara.setBounds(453, 51, 81, 25);
        getContentPane().add(txt_ara);
        txt_ara.setBounds(246, 48, 170, 30);

        txt_adi.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(txt_adi);
        txt_adi.setBounds(110, 470, 170, 30);

        txt_turu.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(txt_turu);
        txt_turu.setBounds(110, 530, 170, 30);

        txt_ucret.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(txt_ucret);
        txt_ucret.setBounds(110, 650, 170, 30);

        txt_tarihi.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().add(txt_tarihi);
        txt_tarihi.setBounds(110, 590, 170, 30);

        txt_islemler.setColumns(20);
        txt_islemler.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txt_islemler.setRows(5);
        jScrollPane2.setViewportView(txt_islemler);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 740, 220, 80);

        txt_nedeni.setColumns(20);
        txt_nedeni.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txt_nedeni.setRows(5);
        jScrollPane3.setViewportView(txt_nedeni);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 480, 220, 80);

        txt_durumu.setColumns(20);
        txt_durumu.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txt_durumu.setRows(5);
        jScrollPane4.setViewportView(txt_durumu);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(410, 610, 220, 80);

        jLabel1.setText("Ücreti");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 630, 100, 16);

        jLabel2.setText("Yapılan İşlemler");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 710, 100, 16);

        jLabel3.setText("Cihaz Türü");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 510, 100, 16);

        jLabel4.setText("Tarih");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 570, 100, 16);

        jLabel5.setText("Adı Soyadı");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 440, 100, 16);

        jLabel6.setText("Cihaz Arızası");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 450, 100, 16);

        jLabel7.setText("Cihaz Durumu");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 580, 100, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        
        int row=table_musteriler.getSelectedRow();
        String secim_yap=(table_musteriler.getValueAt(row, 0).toString());
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
             
            String sorgu21 = "Delete from musteriler where adi_soyadi='"+secim_yap+"'";
      
            st.executeUpdate(sorgu21);
             
            JOptionPane.showMessageDialog(null, "Seçilen Kayıt Silindi. Lütfen Tabloyu Yenileyin.");
            
        } catch (ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }//GEN-LAST:event_btn_silActionPerformed

    private void table_musterilerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_table_musterilerAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_table_musterilerAncestorAdded

    private void table_musterilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_musterilerMouseClicked
        
        
        int row=table_musteriler.getSelectedRow();
        String secim_yap=(table_musteriler.getValueAt(row, 0).toString());
        
        String baslik[] = new String[]{"Ad Soyad", "Cihaz Türü", "Nedeni", "Durumu", "Tarihi", "İşlemler", "Ücret"};  
        

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
            
            String sorgu21 = "select * from musteriler where adi_soyadi='"+secim_yap+"'";
            rs = st.executeQuery(sorgu21);
            

            if(rs.next()) {
 
                txt_adi.setText(rs.getString("adi_soyadi"));
                txt_turu.setText(rs.getString("turu"));
                txt_nedeni.setText(rs.getString("nedeni"));
                txt_durumu.setText(rs.getString("durumu"));
                txt_tarihi.setText(rs.getString("tarihi"));
                txt_islemler.setText(rs.getString("islemler"));
                txt_ucret.setText(rs.getString("ucreti"));
               
            }
           
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }//GEN-LAST:event_table_musterilerMouseClicked

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        
        int row=table_musteriler.getSelectedRow();
        String secim_yap=(table_musteriler.getValueAt(row, 0).toString());
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
             
            String sorgu21 = "UPDATE musteriler SET adi_soyadi='"+secim_yap+"' , turu='"+txt_turu.getText()+
                    "' , nedeni='"+txt_nedeni.getText()+
                    "' , durumu='"+txt_durumu.getText()+
                    "' , tarihi='"+txt_tarihi.getText()+
                    "' , islemler='"+txt_islemler.getText()+
                    "' , ucreti='"+txt_ucret.getText()+
                    "' where adi_soyadi='"+secim_yap+"'";
      
            st.executeUpdate(sorgu21);
             
            JOptionPane.showMessageDialog(null, "Seçilen Kayıt Güncellendi. Lütfen Tabloyu Yenileyin.");
            
        } catch (ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        
        String baslik[] = new String[]{"Ad Soyad", "Cihaz Türü", "Nedeni", "Durumu", "Tarihi", "İşlemler", "Ücret"};  
         
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();
            
            String sorgu21 = "select * from musteriler where adi_soyadi like '%"+txt_ara.getText()+"%'";
            rs = st.executeQuery(sorgu21);
            
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("adi_soyadi"),
                    rs.getString("turu"),
                    rs.getString("nedeni"),
                    rs.getString("durumu"),
                    rs.getString("tarihi"),  
                    rs.getString("islemler"),
                    rs.getString("ucreti")
                };
                i++;
            }
           
            table_musteriler.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }//GEN-LAST:event_btn_araActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kullaiciliste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kullaiciliste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kullaiciliste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kullaiciliste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kullaiciliste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_musteriler;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_ara;
    private javax.swing.JTextArea txt_durumu;
    private javax.swing.JTextArea txt_islemler;
    private javax.swing.JTextArea txt_nedeni;
    private javax.swing.JTextField txt_tarihi;
    private javax.swing.JTextField txt_turu;
    private javax.swing.JTextField txt_ucret;
    // End of variables declaration//GEN-END:variables
}
