/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA
 */
public class kullanici extends javax.swing.JFrame {

    /**
     * Creates new form kullanıcı
     */
    public kullanici() {
        
        super("Müşteri Ekleme Paneli");
        
        initComponents();
        
        String[] Aylar = { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
            "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"};
 
        
            Calendar takvim = Calendar.getInstance();
            String tarih = takvim.get(Calendar.DATE) + " " + Aylar[takvim.get(Calendar.MONTH)]
                    + " " + takvim.get(Calendar.YEAR);
            
            txt_tarihi.setText(tarih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_turu = new javax.swing.JComboBox<>();
        txt_adi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_nedeni = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tarihi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_ucreti = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_durumu = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 640));
        setPreferredSize(new java.awt.Dimension(450, 640));
        getContentPane().setLayout(null);

        jLabel1.setText("Müşteri Adı - Soyadı");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 71, 115, 16);

        jLabel2.setText("Cihaz Türü");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(33, 105, 62, 16);

        c_turu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cep Telefonu", "Tablet", "Bilgisayar" }));
        getContentPane().add(c_turu);
        c_turu.setBounds(182, 105, 170, 27);
        getContentPane().add(txt_adi);
        txt_adi.setBounds(182, 57, 170, 30);

        jLabel3.setText("Cihaz Arıza Nedeni");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(33, 145, 107, 16);

        txt_nedeni.setColumns(20);
        txt_nedeni.setRows(5);
        jScrollPane1.setViewportView(txt_nedeni);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(182, 145, 170, 120);

        jLabel4.setText("Teslim  Tarihi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 450, 79, 16);

        jLabel5.setText("Cihazın Durumu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 300, 90, 16);
        getContentPane().add(txt_tarihi);
        txt_tarihi.setBounds(180, 440, 170, 30);

        jButton1.setText("EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 550, 59, 25);

        jLabel6.setText("Ücret");
        jLabel6.setMinimumSize(new java.awt.Dimension(450, 480));
        jLabel6.setPreferredSize(new java.awt.Dimension(450, 480));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 500, 90, 20);
        getContentPane().add(txt_ucreti);
        txt_ucreti.setBounds(180, 490, 170, 30);

        txt_durumu.setColumns(20);
        txt_durumu.setRows(5);
        jScrollPane2.setViewportView(txt_durumu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 290, 170, 110);

        jButton2.setText("ÇIKIŞ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 10, 63, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{

            String adi=txt_adi.getText();
            String turu=String.valueOf(c_turu.getSelectedItem());
            String nedeni=txt_nedeni.getText();
            String durumu=txt_durumu.getText();
            String ucreti=txt_ucreti.getText();
            String tarihi=txt_tarihi.getText();
            
            if (adi.equals("") || nedeni.equals("")) {
                JOptionPane.showMessageDialog(this, "Boş Alanları Doldurunuz.");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/ariza_takip?useUnicode=true&characterEncoding=UTF-8", "root", "");
                st = con.createStatement();

                String sql = "INSERT INTO musteriler (adi_soyadi,turu,nedeni,durumu,ucreti)"
                + " VALUES ('"+adi+"', '"+turu+"', '"+nedeni+"', '"+durumu+"','"+tarihi+"' '"+ucreti+"')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, " "+adi + " Adlı Müşteri Eklenmiştir.");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        kullanici kapat = new kullanici();
        kapat.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_turu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextArea txt_durumu;
    private javax.swing.JTextArea txt_nedeni;
    private javax.swing.JTextField txt_tarihi;
    private javax.swing.JTextField txt_ucreti;
    // End of variables declaration//GEN-END:variables
}
