/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartproje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author delll
 */
public class ogrenci extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt=null;
    ResultSet rs=null;
    
    
     public void baglan() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost/apart", "root", "");
        
    } 
     public void mesajekle() throws SQLException {


        String baslik[] = new String[]{"msj_odano", "msj_adisoyadi", "mesaj"};

        try {
            baglan();

            String sorgu = "select * from mesajlar";

            stmt = conn.createStatement();
             rs = stmt.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();


            Object data[][] = new Object[kayitsayisi][];
            int i = 0;
            while (rs.next()) {

                data[i] = new Object[]{
                    
                    rs.getString("msj_odano"),
                    rs.getString("msj_adisoyadi"),
                    rs.getString("mesaj")
                };
                i++;
            }
            conn.close();
            jTable1.setModel(new DefaultTableModel(data, baslik));
        } catch (Exception ex) {
        }

    }
    public ogrenci() throws SQLException {
        initComponents();
        mesajekle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mesajlar = new javax.swing.JTextArea();
        msj_odano = new javax.swing.JTextField();
        msj_adisoyadi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ogr_ad = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel7.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "AD", "SOYAD", "Daire NO", "TOPLAM BORÇ", "ÖDEME ŞEKLİ", "TAKSİT SAYISI", "DEPOZİTO", "AÇIKLAMA", "Ödenmiş Taksit Sayisi"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(0, 0, 720, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel2.setMinimumSize(null);
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel7.add(jLabel2);
        jLabel2.setBounds(-10, -40, 760, 480);

        jTabbedPane5.addTab("ÖDEME PLANIM", jPanel7);

        jPanel8.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ad Soyad :");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(20, 60, 120, 17);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ok.png"))); // NOI18N
        jButton7.setText("GÖNDER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7);
        jButton7.setBounds(570, 150, 120, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("İSTEK / ŞİKAYET :");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(20, 90, 120, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Oda No :");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(20, 30, 120, 17);

        mesajlar.setColumns(20);
        mesajlar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mesajlar.setRows(5);
        jScrollPane2.setViewportView(mesajlar);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(170, 90, 520, 50);

        msj_odano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(msj_odano);
        msj_odano.setBounds(170, 30, 125, 25);

        msj_adisoyadi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        msj_adisoyadi.setName("msj_adisoyadi"); // NOI18N
        jPanel8.add(msj_adisoyadi);
        msj_adisoyadi.setBounds(170, 60, 125, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel8.setMinimumSize(null);
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel8.add(jLabel8);
        jLabel8.setBounds(-30, -10, 760, 480);

        jTabbedPane5.addTab("İSTEK / ŞİKAYET", jPanel8);

        getContentPane().add(jTabbedPane5);
        jTabbedPane5.setBounds(10, 90, 730, 230);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/1464592347_exit.png"))); // NOI18N
        jButton6.setText("Çıkış Yap");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(637, 10, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ÖĞRENCİ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 69, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Öğrenci Adı");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 50, 80, 17);

        ogr_ad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(ogr_ad);
        ogr_ad.setBounds(120, 50, 125, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/medical-06-20.png"))); // NOI18N
        jButton10.setText("Ödeme Planımı Göster");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(260, 50, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel3.setMinimumSize(null);
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void aratablodoldur(String ad) throws SQLException {

        String gelenad=ad;
        String baslik[] = new String[]{"ogr_ad", "ogr_soyad", "ogr_dno", "ogr_borc", "ogr_odeme", "ogr_taksit", "ogr_depozito", "ogr_aciklama","odenmis_taksit_sayisi"};

        try {
            baglan();

            String sorgu = "select * from ogrenci where ogr_ad like '%"+gelenad+"%'";
          
            stmt = conn.createStatement();
             rs = stmt.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();


            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    
                    rs.getString("ogr_ad"),
                    rs.getString("ogr_soyad"),
                    rs.getString("ogr_dno"),
                    rs.getString("ogr_borc"),
                    rs.getString("ogr_odeme"),
                    rs.getString("ogr_taksit"),
                    rs.getString("ogr_depozito"),
                    rs.getString("ogr_aciklama"),
                    rs.getString("odenmis_taksit_sayisi")
                };
                i++;
            }
            conn.close();
            jTable4.setModel(new DefaultTableModel(data, baslik));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "HATA!!");
        }}
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String msjodano = msj_odano.getText();
        String msjadi = msj_adisoyadi.getText();
        String mesaj =mesajlar.getText();
        jTable1.hide();
        try {

            baglan();
            String sorgu = "Mesaj Gönderilsin mi?";
            JOptionPane.showMessageDialog(rootPane, sorgu);
            PreparedStatement stmt=conn.prepareStatement("insert into mesajlar(msj_odano,msj_adisoyadi,mesaj) values(?,?,?)");
            stmt.setString(1, msjodano);
            stmt.setString(2, msjadi);
            stmt.setString(3, mesaj);
            stmt.execute();
            
            conn.close();
            mesajekle();
            jTable1.hide();
              } catch (Exception ex) {
            
            Logger.getLogger(ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        giris girissayfa=new giris();
        girissayfa.setVisible(true);
        this.hide();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        try {
            String gidenad=ogr_ad.getText();
            aratablodoldur(gidenad);
        }
        catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ogrenci().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ogrenci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea mesajlar;
    private javax.swing.JTextField msj_adisoyadi;
    private javax.swing.JTextField msj_odano;
    private javax.swing.JTextField ogr_ad;
    // End of variables declaration//GEN-END:variables
}
