/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartproje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author özlem kuşcu
 */
public class ögrsil extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt=null;
    ResultSet rs=null;
    
    public void baglan() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost/apart", "root", "");
    } 
    
    public void tablodoldur() throws SQLException {


        String baslik[] = new String[]{"ogr_id", "ogr_tc", "ogr_ad", "ogr_soyad", "ogr_okul", "ogr_bolum", "ogr_tel","ogr_dno","ogr_yno", "ogr_borc", "ogr_odeme", "ogr_taksit", "ogr_depozito", "ogr_aciklama"};

        try {
            baglan();

            String sorgu = "select * from ogrenci";

            stmt = conn.createStatement();
             rs = stmt.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();


            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    rs.getInt("ogr_id"),
                    rs.getString("ogr_tc"),
                    rs.getString("ogr_ad"),
                    rs.getString("ogr_soyad"),
                    rs.getString("ogr_okul"),
                    rs.getString("ogr_bolum"),
                    rs.getString("ogr_tel"),
                    rs.getString("ogr_dno"),
                    rs.getString("ogr_yno"),
                    rs.getString("ogr_borc"),
                    rs.getString("ogr_odeme"),
                    rs.getString("ogr_taksit"),
                    rs.getString("ogr_depozito"),
                    rs.getString("ogr_aciklama")
                };
                i++;
            }
            conn.close();
            jTable1.setModel(new DefaultTableModel(data, baslik));
        } catch (Exception ex) {
        }

    }
    public void aratablodoldur(String ad) throws SQLException {

        String gelenad=ad;
        String baslik[] = new String[]{"ogr_id", "ogr_tc", "ogr_ad", "ogr_soyad", "ogr_okul", "ogr_bolum", "ogr_tel","ogr_dno","ogr_yno", "ogr_borc", "ogr_odeme", "ogr_taksit", "ogr_depozito", "ogr_aciklama"};

        try {
            baglan();

            String sorgu = "select * from ogrenci where ogr_ad like '%"+gelenad+"%'";
          
            stmt = conn.createStatement();
             rs = stmt.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();


            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    rs.getInt("ogr_id"),
                    rs.getString("ogr_tc"),
                    rs.getString("ogr_ad"),
                    rs.getString("ogr_soyad"),
                    rs.getString("ogr_okul"),
                    rs.getString("ogr_bolum"),
                    rs.getString("ogr_tel"),
                    rs.getString("ogr_dno"),
                    rs.getString("ogr_yno"),
                    rs.getString("ogr_borc"),
                    rs.getString("ogr_odeme"),
                    rs.getString("ogr_taksit"),
                    rs.getString("ogr_depozito"),
                    rs.getString("ogr_aciklama")
                };
                i++;
            }
            conn.close();
            jTable1.setModel(new DefaultTableModel(data, baslik));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "HATA!!");
        }
    
    }
    
    public ögrsil() throws SQLException {
        initComponents();
        tablodoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONEL İŞLEMLERİ-ÖĞRENCİ SİL");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Öğrenci Adı");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(28, 42, 69, 17);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 40, 120, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/search.png"))); // NOI18N
        jButton1.setText("BUL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 40, 100, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/delete_user-20.png"))); // NOI18N
        jButton2.setText("SİL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 40, 100, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/cancel.png"))); // NOI18N
        jButton6.setText("İptal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(520, 40, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 710, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel2.setMinimumSize(null);
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
        baglan();
       
        String tablodangelen = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        JOptionPane.showMessageDialog(rootPane,tablodangelen );
        stmt = conn.createStatement();
        String sql = "DELETE FROM ogrenci "
                + "WHERE ogr_id = " + tablodangelen;
        stmt.executeUpdate(sql);
         tablodoldur();
        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        personel personelsayfasi=new personel();
        personelsayfasi.setVisible(true);
        this.hide();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        String gidenad=jTextField1.getText();
        aratablodoldur(gidenad);
       }
       catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ögrsil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ögrsil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ögrsil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ögrsil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                  new ögrsil().setVisible(true);
    
                } catch (SQLException ex) {
                    Logger.getLogger(ögrsil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void tablodoldur(String gidenad) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
