/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartproje;
import com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author özlem kuşcu
 */
public class ögreklefrm extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt=null;
    ResultSet rs=null;
    
    public void baglan() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost/apart", "root", "");
    } 
    
    public void tablodoldur() throws SQLException {


        String baslik[] = new String[]{"ogr_id", "ogr_tc", "ogr_ad", "ogr_soyad", "ogr_okul", "ogr_bolum", "ogr_tel", "ogr_dno", "ogr_yno", "ogr_borc", "ogr_odeme", "ogr_taksit", "ogr_depozito", "ogr_aciklama"};

        try {
            baglan();

            String sorgu = "select * from ogrenci";

            stmt = conn.createStatement();
             rs = stmt.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();


            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    rs.getInt("ogr_id"),
                    rs.getString("ogr_tc"),
                    rs.getString("ogr_ad"),
                    rs.getString("ogr_soyad"),
                    rs.getString("ogr_okul"),
                    rs.getString("ogr_bolum"),
                    rs.getString("ogr_tel"),
                    rs.getString("ogr_dno"),
                    rs.getString("ogr_yno"),
                    rs.getString("ogr_borc"),
                    rs.getString("ogr_odeme"),
                    rs.getString("ogr_taksit"),
                    rs.getString("ogr_depozito"),
                    rs.getString("ogr_aciklama")
                };
                i++;
            }
            conn.close();
            jTable1.setModel(new DefaultTableModel(data, baslik));
        } catch (Exception ex) {
        }

    }
    public ögreklefrm() throws SQLException {
        initComponents();
        tablodoldur();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ogr_ad = new javax.swing.JTextField();
        ogr_soyad = new javax.swing.JTextField();
        ogr_bolum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ogr_tel = new javax.swing.JTextField();
        ogr_okul = new javax.swing.JTextField();
        ogr_tc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ogr_dno = new javax.swing.JTextField();
        ogr_yno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ogr_borc = new javax.swing.JTextField();
        ogr_odeme = new javax.swing.JTextField();
        ogr_taksit = new javax.swing.JTextField();
        ogr_depozito = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ogr_aciklama = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        odenmis_taksit_sayisi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONEL İŞLEMLERİ-ÖĞRENCİ EKLE");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/cancel.png"))); // NOI18N
        jButton6.setText("İptal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(630, 420, 100, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ok.png"))); // NOI18N
        jButton7.setText("Kaydet");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(520, 420, 100, 30);

        jPanel7.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adı");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(20, 50, 30, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Soyadı");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(20, 80, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Okulu");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(20, 110, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bölümü");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(360, 20, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tel");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(360, 50, 50, 17);

        ogr_ad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_ad);
        ogr_ad.setBounds(130, 50, 125, 25);

        ogr_soyad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_soyad);
        ogr_soyad.setBounds(130, 80, 125, 25);

        ogr_bolum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_bolum);
        ogr_bolum.setBounds(430, 20, 125, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TC Kimlik no");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(20, 20, 80, 17);

        ogr_tel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_tel);
        ogr_tel.setBounds(430, 50, 125, 25);

        ogr_okul.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_okul);
        ogr_okul.setBounds(130, 110, 125, 25);

        ogr_tc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_tc);
        ogr_tc.setBounds(130, 20, 125, 25);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Yatak no");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(360, 110, 60, 20);

        ogr_dno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_dno);
        ogr_dno.setBounds(430, 80, 125, 25);

        ogr_yno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.add(ogr_yno);
        ogr_yno.setBounds(430, 110, 125, 25);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Daire no");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(360, 80, 60, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel2.setMinimumSize(null);
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel7.add(jLabel2);
        jLabel2.setBounds(-10, -40, 740, 380);

        jTabbedPane5.addTab("ÖĞRENCİ VE ODA BİLGİLERİ", jPanel7);

        jPanel8.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Toplam Borç");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(20, 20, 80, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ödeme Türü");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(20, 50, 77, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ödenmiş Taksit Sayısı");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(20, 110, 140, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Depozito");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(410, 20, 60, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Açıklama");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(410, 50, 60, 17);

        ogr_borc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(ogr_borc);
        ogr_borc.setBounds(180, 20, 125, 25);

        ogr_odeme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(ogr_odeme);
        ogr_odeme.setBounds(180, 50, 125, 25);

        ogr_taksit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(ogr_taksit);
        ogr_taksit.setBounds(180, 80, 125, 25);

        ogr_depozito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(ogr_depozito);
        ogr_depozito.setBounds(490, 20, 125, 25);

        ogr_aciklama.setColumns(20);
        ogr_aciklama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ogr_aciklama.setRows(5);
        jScrollPane1.setViewportView(ogr_aciklama);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(490, 50, 125, 80);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Taksit Sayısı");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(20, 80, 80, 17);

        odenmis_taksit_sayisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(odenmis_taksit_sayisi);
        odenmis_taksit_sayisi.setBounds(180, 110, 125, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel8.setMinimumSize(null);
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel8.add(jLabel8);
        jLabel8.setBounds(-10, -40, 760, 480);

        jTabbedPane5.addTab("ÖDEME BİLGİLERİ", jPanel8);

        getContentPane().add(jTabbedPane5);
        jTabbedPane5.setBounds(0, 10, 730, 210);
        jTabbedPane5.getAccessibleContext().setAccessibleName("DAİRE BİLGİLERİ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 720, 140);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartproje/ai.jpg"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel9.setMinimumSize(null);
        jLabel9.setName(""); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 760, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 
personel personelsayfasi=new personel();
personelsayfasi.setVisible(true);
this.hide();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String gelentc = ogr_tc.getText();
        String gelenad = ogr_ad.getText();
        String gelensoyad = ogr_soyad.getText();
        String gelenokul = ogr_okul.getText();
        String gelenbolum = ogr_bolum.getText();
        String gelentel = ogr_tel.getText();
        String gelendaire = ogr_dno.getText();
        String gelenyatak = ogr_yno.getText();
        String gelenborc = ogr_borc.getText();
        String gelenodeme = ogr_odeme.getText();
        String gelentaksit = ogr_taksit.getText();
        String gelendepozito = ogr_depozito.getText();
        String gelenaciklama = ogr_aciklama.getText();
        String odenmistaksitsayisi= odenmis_taksit_sayisi.getText();
        try {

            baglan();
            String sorgu = "eklensin mi?";
            JOptionPane.showMessageDialog(rootPane, sorgu);
            PreparedStatement stmt=conn.prepareStatement("insert into ogrenci(ogr_tc, ogr_ad, ogr_soyad, ogr_okul,ogr_bolum,ogr_tel,ogr_dno,ogr_yno,ogr_borc,ogr_odeme,ogr_taksit,ogr_depozito,ogr_aciklama,odenmis_taksit_sayisi) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            stmt.setString(1, gelentc);
            stmt.setString(2, gelenad);
            stmt.setString(3, gelensoyad);
            stmt.setString(4, gelenokul);
            stmt.setString(5, gelenbolum);
            stmt.setString(6, gelentel);
            stmt.setString(7, gelendaire);
            stmt.setString(8, gelenyatak);
            stmt.setString(9, gelenborc);
            stmt.setString(10, gelenodeme);
            stmt.setString(11, gelentaksit);
            stmt.setString(12, gelendepozito);
            stmt.setString(13, gelenaciklama);
           stmt.setString(14, odenmistaksitsayisi);
            stmt.execute();
            
            conn.close();
            tablodoldur();
        } catch (Exception ex) {
            
            Logger.getLogger(ögreklefrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ögreklefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ögreklefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ögreklefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ögreklefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                  new ögreklefrm().setVisible(true);
    
                } catch (SQLException ex) {
                    Logger.getLogger(ögreklefrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField odenmis_taksit_sayisi;
    private javax.swing.JTextArea ogr_aciklama;
    private javax.swing.JTextField ogr_ad;
    private javax.swing.JTextField ogr_bolum;
    private javax.swing.JTextField ogr_borc;
    private javax.swing.JTextField ogr_depozito;
    private javax.swing.JTextField ogr_dno;
    private javax.swing.JTextField ogr_odeme;
    private javax.swing.JTextField ogr_okul;
    private javax.swing.JTextField ogr_soyad;
    private javax.swing.JTextField ogr_taksit;
    private javax.swing.JTextField ogr_tc;
    private javax.swing.JTextField ogr_tel;
    private javax.swing.JTextField ogr_yno;
    // End of variables declaration//GEN-END:variables
}
