/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surucukursuotomasyonu;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class ogretmenler extends javax.swing.JFrame {

    /**
     * Creates new form ogretmenler
     */
    public ogretmenler() {
        initComponents();
         try {
        Class.forName("com.mysql.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root",""); //Mysql sunucusuna bağlandık
        java.sql.Statement st = (java.sql.Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from ogretmenbilgi")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
        }
        
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_bilgi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_giris = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        txt_gorev = new javax.swing.JTextField();
        txt_maas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        table_bilgi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_bilgi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bilgiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_bilgi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 800, 132);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 210, 110, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 210, 110, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 210, 110, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Giriş Tarihi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 300, 70, 16);
        getContentPane().add(txt_giris);
        txt_giris.setBounds(140, 290, 110, 30);
        getContentPane().add(txt_adi);
        txt_adi.setBounds(140, 340, 110, 30);
        getContentPane().add(txt_gorev);
        txt_gorev.setBounds(380, 290, 110, 30);

        txt_maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_maas);
        txt_maas.setBounds(380, 340, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Adı Soyadı");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 350, 68, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Görev");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 300, 38, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Maaş");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 350, 40, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\sefabingoljavatasarim\\background.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           String gorev1=txt_gorev.getText();
            String adi_soyadi1=txt_adi.getText();
            String maas=txt_maas.getText(); 
                   String giris_tarihi=txt_giris.getText();
            
            if (gorev1.equals("") || adi_soyadi1.equals("")|| maas.equals("")|| giris_tarihi.equals("")){

                JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

            } else {            
                Class.forName("com.mysql.jdbc.Driver");

                java.sql.Connection con = null;
                java.sql.Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root","");
                
                st =(java.sql.Statement) con.createStatement();

                String sql = "INSERT INTO ogretmenbilgi (giris_tarihi,adi_soyadi,gorev,maas)" 
                        + " VALUES ('"+giris_tarihi+"','"+adi_soyadi1+"', '"+gorev1+"', '"+maas+"')";

                st.executeUpdate(sql); //
                JOptionPane.showMessageDialog(null,"Öğretmen Bilgisi Eklenmiştir");
       }
       }
       catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        try {
        Class.forName("com.mysql.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root",""); //Mysql sunucusuna bağlandık
        java.sql.Statement st = (java.sql.Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from ogretmenbilgi")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
        }
        
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_maasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maasActionPerformed

    private void table_bilgiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bilgiMouseClicked
        String giris_tarihi = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 0).toString();
        String adi_soyadi = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 1).toString();
        String gorev = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 2).toString();
        String maas = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 3).toString();
        
       
        
        txt_giris.setText(giris_tarihi);
                txt_adi.setText(adi_soyadi);

        txt_gorev.setText(gorev);
        txt_maas.setText(maas);
        
    }//GEN-LAST:event_table_bilgiMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try
{
           
           
            String adi_soyadi=txt_adi.getText();
           
            
            
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root","");
                st =(Statement) con.createStatement();
                String sql="DELETE FROM `ogretmenbilgi` WHERE adi_soyadi='"+adi_soyadi+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Öğretmen Bilgisi Silinmiştir.");
                txt_adi.setText("");
                txt_gorev.setText("");
                txt_maas.setText("");
                txt_giris.setText("");
                
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmenbilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ogretmenbilgi.class.getName()).log(Level.SEVERE, null, ex);
        }

try {
        Class.forName("com.mysql.jdbc.Driver");
        try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root","") //Mysql sunucusuna bağlandık
                ) {             java.sql.Statement st = (java.sql.Statement) con.createStatement();
                try (ResultSet rs = st.executeQuery("Select * from ogretmenbilgi")) { //Veritabanındaki tabloya bağlandık
                    int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
                    DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
                    for(int i = 1;i<=colcount;i++)
                        tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
                    while(rs.next())
                    {
                        Object[] row = new Object[colcount];
                        for(int i=1;i<=colcount;i++)
                            row[i-1] = rs.getObject(i);
                        tm.addRow(row);
                    }
                    table_bilgi.setModel(tm);
                }
        }
        } catch (SQLException ex) {
            Logger.getLogger(ogretmenbilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmenbilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
            String adi_soyadi=txt_adi.getText();
            String maas=txt_maas.getText();
            String gorev=txt_gorev.getText();
          String giris_tarihi=txt_giris.getText();
          
            
           
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root","");
                st =(Statement) con.createStatement();
                String sql="UPDATE `ogretmenbilgi` SET giris_tarihi='"+giris_tarihi+"', adi_soyadi='"+adi_soyadi+"', gorev='"+gorev+"', maas='"+maas+"' WHERE adi_soyadi='"+adi_soyadi+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Öğretmen Durumu Güncellenmiştir.");
                txt_giris.setText("");
                txt_adi.setText("");
                txt_gorev.setText("");
                txt_maas.setText("");
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ogretmenler.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
        Class.forName("com.mysql.jdbc.Driver");
        try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/surucukursu","root","") //Mysql sunucusuna bağlandık
                ) {             java.sql.Statement st = (java.sql.Statement) con.createStatement();
                try (ResultSet rs = st.executeQuery("Select * from ogretmenbilgi")) { //Veritabanındaki tabloya bağlandık
                    int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
                    DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
                    for(int i = 1;i<=colcount;i++)
                        tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
                    while(rs.next())
                    {
                        Object[] row = new Object[colcount];
                        for(int i=1;i<=colcount;i++)
                            row[i-1] = rs.getObject(i);
                        tm.addRow(row);
                    }
                    table_bilgi.setModel(tm);
                }
        }
        } catch (SQLException ex) {
            Logger.getLogger(sertifika.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sertifika.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogretmenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogretmenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogretmenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogretmenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogretmenler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_bilgi;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_giris;
    private javax.swing.JTextField txt_gorev;
    private javax.swing.JTextField txt_maas;
    // End of variables declaration//GEN-END:variables
}
